In [1]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\acer\data-journey-60days\venv\Scripts\python.exe
3.13.13 (tags/v3.13.13:01104ce, Apr  7 2026, 19:25:48) [MSC v.1944 64 bit (AMD64)]

In [19]:
import pandas as pd
df = pd.read_csv("Banking Customer Churn Prediction Dataset.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [18]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [21]:
display(df.head())
display(df.tail())

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df.shape

(10000, 14)

In [9]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [22]:
print(df['Tenure'])

0        2
1        1
2        8
3        1
4        2
        ..
9995     5
9996    10
9997     7
9998     3
9999     4
Name: Tenure, Length: 10000, dtype: int64

In [23]:
df['Tenure'] # Series — одна колонка как список

0        2
1        1
2        8
3        1
4        2
        ..
9995     5
9996    10
9997     7
9998     3
9999     4
Name: Tenure, Length: 10000, dtype: int64

In [24]:
df[['Tenure']] # Series — одна колонка как Data Frame

      Tenure
0          2
1          1
2          8
3          1
4          2
...      ...
9995       5
9996      10
9997       7
9998       3
9999       4

[10000 rows x 1 columns]

In [26]:
df.iloc[24]

RowNumber                 25
CustomerId          15625047
Surname                  Yen
CreditScore              846
Geography             France
Gender                Female
Age                       38
Tenure                     5
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    187616.16
Exited                     0
Name: 24, dtype: object

In [29]:
df.iloc[499:505]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
499,500,15677020,Selezneva,570,France,Female,58,8,0.00,1,0,1,116503.92,1
500,501,15727688,Chizuoke,555,Spain,Male,32,4,0.00,2,1,1,54405.79,0
501,502,15715941,Lueck,692,France,Male,54,5,0.00,2,1,1,88721.84,0
502,503,15714485,Udinese,774,France,Male,60,5,85891.55,1,1,0,74135.48,1
503,504,15730059,Udobata,638,Spain,Male,44,9,77637.35,2,1,1,111346.22,0
504,505,15715527,Freeman,543,Spain,Female,41,4,0.00,1,0,0,194902.16,0

In [31]:
df.iloc[503,2]

'Udobata'

In [38]:
for index, row in df.iterrows():
    print(row['Surname'], row['Geography'])

Hargrave France
Hill Spain
Onio France
Boni France
Mitchell Spain
Chu Spain
Bartlett France
Obinna Germany
He France
H? France
Bearce France
Andrews Spain
Kay France
Chin France
Scott Spain
Goforth Germany
Romeo Germany
Henderson Spain
Muldrow Spain
Hao France
McDonald France
Dellucci Spain
Gerasimov Spain
Mosman France
Yen France
Maclean France
Young Germany
Nebechi France
McWilliams Germany
Lucciano France
Azikiwe Spain
Odinakachukwu France
Sanderson Germany
Maggard Spain
Clements Spain
Lombardo France
Watson Spain
Lorenzo Spain
Armstrong France
Cameron Germany
Hsiao Spain
Clarke France
Osborne France
Lavine France
Bianchi Spain
Tyler Germany
Martin Germany
Okagbue Germany
Yin Germany
Buccho Germany
Chidiebele Germany
Trevisani Germany
O'Brien France
Parkhill Germany
Yoo Germany
Phillipps France
Tsao France
Endrizzi Germany
T'ien Spain
Velazquez France
Hunter Germany
Clark Germany
Jeffrey Spain
Pirozzi Spain
Jackson Germany
Hammond Germany
Brownless Germany
Chibugo Germany
Glauert Germany
Pisano France
Konovalova Germany
McKee France
Palermo Spain
Ballard Germany
Wallace France
Cavenagh France
Hu France
Read France
Bushell Spain
Postle Germany
Buley France
Leonard France
Mills France
Onyeorulu France
Beit France
Ndukaku Spain
Gant Spain
Rowley France
Sharpe France
Osborne Germany
Heap Spain
Ritchie France
Cole France
Capon France
Capon Spain
Fiorentini Spain
Graham Spain
Yuille Germany
Allard Spain
Fanucci France
Fu France
Hung France
Hung France
Bradley Spain
Dunbabin Spain
Mauldon Spain
Stiger Germany
Parsons Germany
Walkom Spain
T'ang Germany
Eremenko Germany
Rowntree Germany
Thorpe France
Chiemela Spain
Fanucci Germany
Ko Germany
Welch Germany
Duncan France
Chidozie Germany
Wu Germany
Culbreth France
Kennedy Spain
Cameron France
Calabresi Germany
Zetticci France
Fuller France
MacDonald France
Piccio Germany
Kennedy France
Fernie France
He France
Kaodilinakachukwu Germany
Cocci France
Alekseeva France
Chinweike Germany
Arthur Germany
Li Germany
Ma France
Chia Spain
Vasin Spain
Groves Germany
Tien France
Forwood France
Greeves Spain
Taylor France
Madukwe Spain
Bennelong Spain
Olisanugo France
Chukwufumnanya France
Harris France
Morgan Spain
Alexeeva France
Metcalfe Spain
Humphries France
Milne France
Chou Spain
Li France
Clayton Spain
Maclean France
Chigolum Germany
Wilkinson Spain
Wei France
Treacy France
Hu Spain
Taverner Spain
Sherman Germany
Taubman Germany
Robinson Spain
Pinto Spain
Wood Germany
Hawkins France
Sun Germany
Yost Germany
Ting France
Rowe France
Fu Spain
Ho France
Okechukwu Germany
Campbell Spain
Ashbolt Germany
Rozier Spain
Hsia France
Ogbonnaya Germany
T'ang France
Cocci France
Chang France
T'ao France
Ford Spain
Marshall Spain
Tsai Germany
Onwumelu France
Graham France
Golovanov France
Potts France
Crawford Spain
Aleshire France
Moran Spain
Samsonova Germany
Jenkins France
Volkov France
Chiemezie Spain
Jude France
He Spain
Onuora France
Ginikanwa Spain
Ku France
McDonald Spain
Collins France
Hackett France
Dike France
Trevisano Germany
Tan France
Glassman France
Miller France
Kornilova Germany
Watson Germany
Marchesi France
Millar Spain
Shih France
Fuller France
Hay France
Yang Spain
McIntyre France
Stevenson France
Poole Germany
Bagley France
Ch'ien France
Cattaneo Germany
O'Sullivan Germany
Lucas Germany
Ringrose France
Freeman France
Sergeyev France
Fiore Germany
Smith France
Dumetochukwu Germany
Pacheco France
Synnot Germany
Johnston France
Stevens France
Grant Spain
Tsao Germany
Barnes France
McIntosh Germany
Madison Spain
Ifesinachi France
Glazkov Germany
Dimauro France
Wieck Germany
Liao Germany
Hughes Germany
Morrison Spain
Matveyeva France
Ku Germany
Cheatham Spain
Yao Spain
Kirkland France
Rose Germany
Jess France
Welch Germany
Ifeajuna Germany
Morton Spain
Rossi France
Reppert France
Kang Spain
Ch'iu Spain
Wallis France
Clark France
Fielding Spain
Zetticci Germany
Dulhunty Spain
Bevington Germany
Boyle Germany
Newton France
Bowman Germany
Dubinina Spain
Toscani France
Chiazagomekpere France
Allen France
K'ung France
Wilsmore France
Hargreaves Spain
Huang Germany
Ch'ien France
Wallwork France
Chu France
Kang Spain
Davidson France
O'Donnell Spain
Nnachetam Spain
Chidiebele Germany
Ahmed Spain
Booth France
Chuang Spain
Shao France
Tsao France
Tien France
Chang Spain
Johnson France
French France
Efremov France
Hartley Spain
Calabrese France
Chiu France
Brennan France
Onwuatuegwu France
Hewitt France
Shih Germany
Balashov France
Doyle Germany
Pokrovskii France
Collins Germany
Russo France
Skinner Germany
Robertson Spain
Atkinson Spain
Doyle France
Ritchie Spain
McEncroe Spain
Pearson France
Gordon Spain
Ts'ai France
Lung France
Yuan France
Pardey France
Tai France
Scott France
Hunter France
Mazzanti Germany
L? Germany
Beach France
Hsieh Spain
Faulkner Germany
Knowles Germany
Day Spain
Hsueh France
Tsao Germany
Kennedy France
Nwabugwu Spain
Young Germany
Kerr Germany
Tien France
Marrero Spain
White France
Pisano France
Brown France
Freeman Germany
Russell Germany
Seleznyov Germany
Yusupova France
Foley Spain
Shih Spain
Ikedinachukwu Spain
Power Spain
Amos France
Reed France
Simmons Spain
Ricci Spain
Yen France
Campbell France
West Spain
Robinson Germany
Bianchi France
Chen Germany
Madukaego France
Ibrahimova Spain
Nolan Germany
Scott Germany
Blair Germany
Monaldo France
Sutherland Spain
Cole Germany
Briggs Germany
Gregory Germany
Bianchi Germany
Angelo France
Gardiner Germany
Kerr Spain
Ko Spain
Distefano Spain
Farrell France
Milano France
Ting Germany
Boyd Germany
Onyemaechi Germany
Black France
Oliver Spain
Greco Spain
Whitehead Spain
Ikemefuna France
Morrison Germany
Onyeoruru Germany
Cunningham Spain
Demidov Spain
Celis Spain
Cheng Germany
Knight France
Morin Germany
Mills France
Outhwaite France
Tung France
Pai Germany
Carpenter Spain
Fennell Spain
Fontaine France
Pratt France
Mitchell Spain
Franklin Spain
K'ung Germany
Ko Germany
McKenzie Spain
Pino France
Fisk Spain
Chiang Germany
Moseley Spain
Hsiung Spain
Heath Germany
Dellucci France
Li France
De Salis France
T'ang Germany
Richardson France
Fitch Germany
Stevenson France
Estes France
Lattimore France
Chung Germany
Utz France
Wei Germany
Boyle Germany
Nwachinemelu Germany
Kuznetsova Germany
Pisani Germany
Manna Germany
Collier France
Ricci France
Carr Germany
Hs? France
Findlay France
Hughes Germany
Chukwuemeka France
Genovese France
Swift France
Ugoji France
Parkinson Spain
Ross France
Oleary France
Turnbull France
Uspensky France
Cook Spain
Newbold Germany
Uchechukwu France
Ch'en Spain
He Spain
Hilton France
Sal France
Eluemuno France
Titus France
Yin Germany
Lettiere Spain
Templeman Germany
Chibuzo France
Sun Spain
Evans France
Ogbonnaya Spain
Enyinnaya France
Olisanugo Spain
Brookes Germany
Padovano France
Fisk France
Shih Spain
Hare France
Muir France
Fanucci France
Elewechi France
Johnston Germany
Pisano Germany
Ankudinov France
Nwokike France
Smith France
Atkins Spain
Burns France
Obiuto France
Pirozzi Germany
George Spain
Lewis France
Moran France
Dalrymple France
Carslaw France
Kirby Germany
Houghton Spain
Martin France
Tan France
Hsia France
Westerberg France
Hale Germany
Kryukova France
Sopuluchukwu France
Barry Germany
Selezneva France
Chizuoke Spain
Lueck France
Udinese France
Udobata Spain
Freeman Spain
Outlaw France
Obiuto Germany
Lo Germany
Okechukwu France
King Spain
Forbes Germany
Macleod Germany
Gibbs Spain
Isayev France
Pisano France
Belstead Spain
Vassiliev France
Schneider Germany
Mazzanti France
Knipe France
Macartney France
Madukwe France
Watts Spain
Humphreys Germany
Wu France
Chin France
Chesnokova France
Kung France
Lu Germany
Nkemakolam France
Walton Spain
Brookes Spain
Baldwin France
Mai Spain
Shih France
He France
Fiorentini Germany
Lucciano Spain
Ferreira Germany
Ukaegbunam Germany
De Luca France
Milne France
Davide France
Kodilinyechukwu Spain
Little France
Burns Spain
Paterson France
Han Germany
Kryukova France
Ijendu France
Reichard Germany
Day Germany
Price Spain
Bruce France
Sumrall Germany
Lu Spain
Lazarev Germany
Miller Germany
Wentworth-Shields Spain
Ritchie Spain
Mackenzie Germany
Power Spain
Tan Spain
Pendergrass France
Evans Spain
Hsia France
Billson Spain
Teng Spain
Moretti Germany
Jordan France
Ts'ao France
Osborne France
Carslaw France
Ch'ang Spain
Hung Spain
Gordon France
Obialo Spain
Gray France
Lin France
Hopkins France
Dobson Spain
McKay Spain
Revell Spain
Rickards Germany
Begum Germany
Onyinyechukwuka France
Zuyev Spain
Nwankwo France
Hao France
Ma Spain
Okwuadigbo Germany
Mitchell France
Chan France
Buchi Spain
Greco Spain
Lombardi Germany
Uchenna Spain
Coffman Germany
Alexandrova Germany
Fallaci Germany
Hudson France
Mai Spain
Stout France
Burke France
Chadwick France
Lawrence France
Bellucci France
Harper France
Boyle France
Duncan Germany
Moss France
Avdeyeva France
Crawford France
Lynton Spain
Duncan Germany
Gether Spain
Davidson Spain
Larionova Germany
Loggia Spain
Steinhoff Spain
Guerra France
Pai Spain
Craig Germany
Lazareva Germany
Ch'iu Spain
Alderete Spain
Kung France
Palermo France
Ts'ai France
Rahman Spain
McMillan France
Pickering Germany
Mirams Spain
Tsao Germany
Douglas France
Jideofor Spain
Bell Spain
Mairinger France
McIntyre France
Pagnotto France
K'ung Spain
Feng France
Donaldson France
Chambers Germany
Marcelo France
Ejimofor France
Dale France
Pokrovsky France
Stonebraker France
Liang France
Anderson France
Christian France
Mao France
Campbell Germany
Ginikanwa Spain
Toscani Germany
Nnachetam Spain
Sagese Germany
Fleming France
Grubb France
Napolitani Germany
Anenechi Spain
Chandler France
Howells France
Akeroyd France
Onwumelu France
Wallace France
Uwaezuoke France
Loyau Spain
Small France
Bledsoe Germany
Kao France
Wickens France
Wertheim Spain
He Spain
Jarvis France
P'an Spain
Repina Germany
Pugliesi Spain
Blakey Spain
Nucci France
Higinbotham Spain
Achebe Germany
Russo Germany
Trevisani France
Dobie Spain
Maccallum France
Watkins Germany
Mitchel France
Ferdinand France
Otitodilinna Germany
Mamelu France
Beneventi Germany
Perrodin France
Chinagorom France
Napolitano France
Edgar Spain
Walker Germany
Steele Spain
Elkins Germany
Hao France
Toscano France
Savage Spain
Okwuadigbo Spain
Mordvinova Germany
Welch Germany
Kent Germany
Campbell France
Cooper France
Mazzi France
Fisher France
Summers Germany
Brady Spain
Nicholls France
Yuan Spain
Robinson France
Golubov Germany
Chen Spain
Oldham France
Kambinachi France
Fleming Spain
Cunningham Spain
Obinna France
Chinwemma France
Carpenter France
Yin France
Olsen France
Ts'ai France
Jen France
Preston France
Ozioma France
Cody France
Ponomarev Spain
Martin Germany
Milani Germany
Tang France
Romani Spain
McIntyre France
Davis France
Onyemauchechukwu France
Gell France
Rossi France
Chiwetelu France
Kirillova France
Shaw France
Smith France
Hsieh France
Onyemauchechukwu Spain
Martin Spain
Okwudilichukwu Germany
Onuoha France
Muecke Germany
Hsieh France
Anderson Germany
Azubuike Spain
Nnonso France
Fuller Germany
Ashley Spain
Ts'ui France
Buccho France
Chidozie France
Maclean France
Burns Germany
Chu Germany
Kenenna Germany
Beluchi Spain
Williamson France
Bobrov Germany
Kerr Spain
McKenzie France
Pitts Germany
Standish France
Cartwright France
Johnstone France
Nikitina Germany
McElroy France
Shen Germany
Archer Spain
Otutodilinna France
Shih Spain
Denisov France
Owens France
P'eng France
Verco France
Bergamaschi Germany
Lorenzo Spain
Outtrim France
Hou Germany
Galkin Spain
Pagnotto Spain
Echezonachukwu France
Young France
Summers Germany
Munro Germany
Brennan France
Ball Germany
Virgo France
Trevisani Germany
Padovano France
Tao Germany
Perez France
Fraser Germany
Alley Germany
Howells Spain
Cameron France
Hooper Spain
Rice France
Cox France
Martin Germany
Ikenna France
Davide France
Alexander Spain
Piazza Spain
Ni Germany
Black France
Harker France
Hughes France
Chiabuotu Germany
Kuo Spain
Gallagher France
Calabresi Germany
Shaw France
Zhirov Spain
Lloyd Spain
Palmer Spain
Ch'eng Germany
Avent France
Huang Spain
Shaw Germany
Yuan France
Hawkins France
Trentini Spain
Cameron Germany
Koehler Germany
Wu France
Manna France
Okoli Spain
Ch'eng Germany
Nwokezuike Spain
Artemiev France
Esposito Germany
Abbie France
Fanucci Germany
Jen Spain
Moss France
Lo France
Averyanov Germany
Unaipon France
Clamp Spain
Lim France
Wu Germany
Wan Germany
Chambers Germany
Pettit France
Baresi France
Newbery Spain
Iheanacho Germany
Duncan Spain
Barry Spain
Landry France
McGregor France
Nucci France
Pirogov France
Oguejiofor France
Ugochukwu France
Rohu Germany
Cary France
O'Loghlen France
Quinn Germany
Page France
Evans France
McGregor Germany
Andrews France
Stanley France
Chiazagomekpere France
Chidiebele France
Gregory Germany
Bednall Spain
Jen France
She France
Simmons France
Fraser France
May France
Seabrook France
Herrera France
Kincaid France
Sleeman Spain
Hung France
Artemieva Germany
Barwell France
Wright Spain
Bellucci Germany
Moore France
Ball France
Sung Germany
Mello Germany
Mistry France
T'ien France
Fallaci France
Hill Germany
Burns Germany
Hunter France
Li France
Ku France
Ch'en France
Chukwukadibia France
Zikoranachidimma France
Oluchukwu France
Rivera Spain
Niu Spain
Bennett France
Wollstonecraft Spain
Thomsen Spain
Palermo Germany
Chinwendu France
McKenzie France
James France
Lamb France
Olejuru Spain
Hay Spain
Lu France
Chiawuotu Spain
Yeates France
Gallagher Germany
Heath France
Ts'ai Germany
Thurgood Spain
Pai Germany
Lorenzo Germany
Knupp France
Baryshnikov Spain
Azubuike Germany
Shephard Germany
Scott Spain
Williamson Spain
Avdeeva France
Tang France
Hsu Germany
Buchanan France
Yeh France
Palazzi Spain
Y?an France
Lin France
Schofield Germany
Lombardi France
Wall Spain
Milani Spain
Ejimofor France
Blackburn France
Wickham France
Bird France
Ch'en Germany
Wood Germany
Brizendine Spain
Ch'in Spain
Yusupov France
Jibunoh Spain
Ts'ui Spain
Ndukaku Spain
Wilder France
Maclean Germany
Ch'iu Spain
Cox Spain
Nepean Spain
McNess Germany
Coles France
Benson France
Gilbert Spain
Wilhelm France
Sinclair Germany
L? France
Buckner France
Padovesi Germany
Gray Spain
Lu France
Wright Spain
Palerma France
Y?an France
Wei France
Padovesi France
Tsao France
Franklin Germany
Clark France
McGregor Germany
Pan France
Kenniff Germany
Spencer France
Lees Spain
David Spain
Hsing France
Burke France
Watson France
Hawkins Germany
Ginn Spain
Sozonov Spain
Sun Spain
Hunter Spain
Manfrin Spain
Artamonova Germany
Hansen France
Pai Germany
Larsen France
Owen Germany
Murphy France
Ekechukwu Germany
Ayers Germany
Johnson Spain
Millar France
Farrell France
Sanders Spain
Herrera France
Eberechukwu Spain
Bardin France
Nwankwo Spain
Talbot Spain
McGregor France
Onyeorulu Germany
Goold Germany
Zikoranaudodimma Germany
Garner France
Onyinyechukwuka France
Genovese Spain
Mai France
Marshall France
Naylor France
Pinto France
Fulton France
Palerma Germany
McCaffrey Spain
Collins Spain
Zuev France
Crawford France
Genovese Spain
Maclean France
Fabro France
Price Spain
Chatfield France
Volkova France
Archer France
Ch'iu France
McKay Spain
Craig France
Abramovich Spain
Chien France
Timms France
Williford Spain
Hamilton Spain
Cheng France
Su Germany
McKenzie Germany
Akobundu France
Ko Spain
Marcelo Germany
Chukwuebuka Spain
MacDonald Spain
Lampungmeiua Spain
Tai Spain
Enyinnaya France
McKenzie Germany
Kline France
Ma Spain
Wood Spain
Riggs Germany
Capon France
Smith France
Davison France
Ingram France
Dilke Germany
Gibson France
Iadanza France
Hebert Germany
Pinto Germany
Dumetochukwu Spain
Ross Spain
Jamieson France
Chiganu Germany
Burgess Spain
Cheng France
Woods Germany
Liang France
Bluett Germany
Chapman Spain
Andrejew Spain
Udobata France
Ejimofor France
Spyer France
Walker France
Palermo France
Philip Spain
Fallaci France
Perry Germany
Henderson France
Bergamaschi France
Fokine France
Mackay France
Wu France
Maslova Germany
Wei France
McLean France
Sung Spain
Paterson France
Fanucci Spain
Thompson Spain
Tisdall Germany
Onochie France
Mironova France
Ndubueze France
Stephenson Germany
Golubev Germany
Liao France
Mullan France
Glover Germany
Northey France
Paterson Germany
Maclean France
Howarde Spain
Teng France
Colman France
Johnson Spain
Butcher Spain
Stanley Germany
Jackson France
Hu Germany
Hill Germany
Pan Spain
Han Germany
Wilkie Spain
Bray Germany
Ann France
Souter France
Greco Germany
Mao Spain
Anderson France
Ma France
Black France
Medvedeva Germany
Benson France
Duncan France
Onwudiwe Germany
Mitchell Spain
Ferrari France
Russo France
Hazon Spain
Henderson France
Hardy Germany
Piccio France
Dickson Germany
Holden Germany
Hsieh Spain
Doherty France
Page France
Samuel Spain
Malloy Germany
Fitts Germany
Iadanza Spain
Wu France
Yefimova France
Pan Spain
Ts'ui Germany
Liang Spain
Tsao France
Abramov France
Millar France
Demuth Germany
Genovese France
Lawless Germany
Brooks Germany
Ignatyeva France
Balmain France
Millar France
Ecuyer Spain
Parkhill Germany
Li Fonti Germany
Beneventi Spain
Despeissis Spain
Atkins Spain
Williams France
Wright France
Hancock France
Hsieh Germany
Wilkins France
Longo Germany
Mancini France
Madukaego France
Winter-Irving Germany
Stewart France
Grant France
Brennan France
She France
Murray France
Rischbieth France
Lung Germany
Otutodilichukwu Spain
Thomas Spain
Fiorentini France
Hughes France
Whitworth Germany
McIntosh Spain
Ayers France
Trentino France
Boyd Germany
McMasters Germany
Alekseyeva France
Miller France
Baranova France
Mitchell France
Yobachi Spain
Huang Germany
Genovese France
Sorokina France
Gray France
Ervin France
Vance Spain
Noble France
Milanesi Spain
Parkin Spain
Cremonesi France
Burns Germany
Docherty France
Ugonna Germany
L? Germany
Bevan France
Hsia France
O'Neill Spain
Johnstone Spain
Pham Spain
Bergamaschi Germany
Murphy France
Osinachi France
Muravyov Spain
Igwebuike Germany
Zack Spain
Crawford Germany
Chidiegwu Germany
Lucchesi France
Pan Germany
Trevisani Germany
Yudin France
Wade France
Chung France
Septimus France
Hargraves France
Chukwukadibia Germany
Sidorov Germany
Bunton Germany
Cameron France
Kung France
Hay France
Conti Spain
Sims France
Carter Germany
McGregor Germany
Lo France
Chu Germany
Dumetolisa France
Peng Spain
Drake-Brockman France
Wan France
Cameron France
Tretiakov Germany
Ball Germany
Sal Germany
Chung Spain
Lai France
Gether Spain
Davidson France
Justice France
Osonduagwuike Germany
Ewing France
Chin France
Chiang Germany
Ahmed France
Marshall Germany
Tsou France
Chien Spain
Ubanwa France
Kapustin Germany
Calabresi France
Hsiao Spain
Grant France
H? Spain
Chia Spain
Ugoji France
Gregory France
Mackay France
Nnamutaezinwa Spain
Findlay Spain
Ferri Spain
Ku Spain
Amechi Germany
Kirk Germany
Andrews Spain
Murray France
Griffin France
Longstaff France
McWilliam Spain
Coffee Spain
Hancock France
Clark France
Creswell Germany
Dodds France
Ewen Spain
Carter France
Ch'iu Germany
Tsao France
Burgess Germany
Fanucci Spain
Blackburn Spain
Bennett France
Boniwell Spain
Vasilieva Germany
Longo France
Kwemto France
Lawrence France
Duncan France
Bocharova Spain
Morres France
Shih France
Vogel France
T'an Germany
Wisdom France
Lorenzo France
Shahan France
Bryant Spain
Liang Germany
Chidozie France
Hayward France
Liu Spain
Alexeeva Germany
Calabresi France
Lettiere Spain
Chou Germany
Nnamutaezinwa France
Nnamutaezinwa Germany
Greece Germany
Yin Spain
Larionova Spain
Golubev Germany
Norman France
Capon Spain
Chukwudi Spain
Fedorov France
Avdeeva Spain
Reid Spain
Kennedy Germany
Chan Spain
Wofford France
Mai France
King France
T'ao Spain
Hsu France
White France
Stephens Germany
Frolov Spain
Lombardi Spain
Munro Spain
Hayward France
Fields France
Onwumelu France
Suffolk France
Tsao Germany
Judd France
Hamilton Germany
T'ang Spain
Degtyarev Germany
Kang France
Hudson Spain
Jibunoh Germany
Kinlaw Spain
Chizuoke Germany
Lucciano France
Omeokachie France
Gorbunova France
Tikhonov Germany
Campa France
Mancini France
Donoghue France
Tuan Spain
Johnstone Spain
Romani Germany
Fuller Germany
Baxter France
Pirozzi Spain
Sung France
Rogers Spain
Mills France
Osonduagwuike France
Byrne France
McIntyre France