In [1]:
import sys
print(sys.executable)
print(sys.version)

C:\Program Files\Python311\python.exe
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [55]:
import pandas as pd
df = pd.read_csv("Banking Customer Churn Prediction Dataset.csv", index_col='RowNumber')
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
display(df.head())
display(df.tail())

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
df.shape

(10000, 14)

In [6]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [8]:
print(df['Tenure'])

0        2
1        1
2        8
3        1
4        2
        ..
9995     5
9996    10
9997     7
9998     3
9999     4
Name: Tenure, Length: 10000, dtype: int64

In [9]:
df['Tenure'] # Series — одна колонка как список

0        2
1        1
2        8
3        1
4        2
        ..
9995     5
9996    10
9997     7
9998     3
9999     4
Name: Tenure, Length: 10000, dtype: int64

In [10]:
df[['Tenure']] # Series — одна колонка как Data Frame

      Tenure
0          2
1          1
2          8
3          1
4          2
...      ...
9995       5
9996      10
9997       7
9998       3
9999       4

[10000 rows x 1 columns]

In [11]:
df.iloc[24]

RowNumber                 25
CustomerId          15625047
Surname                  Yen
CreditScore              846
Geography             France
Gender                Female
Age                       38
Tenure                     5
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    187616.16
Exited                     0
Name: 24, dtype: object

In [12]:
df.iloc[499:505]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
499,500,15677020,Selezneva,570,France,Female,58,8,0.00,1,0,1,116503.92,1
500,501,15727688,Chizuoke,555,Spain,Male,32,4,0.00,2,1,1,54405.79,0
501,502,15715941,Lueck,692,France,Male,54,5,0.00,2,1,1,88721.84,0
502,503,15714485,Udinese,774,France,Male,60,5,85891.55,1,1,0,74135.48,1
503,504,15730059,Udobata,638,Spain,Male,44,9,77637.35,2,1,1,111346.22,0
504,505,15715527,Freeman,543,Spain,Female,41,4,0.00,1,0,0,194902.16,0

In [13]:
df.iloc[503,2]

'Udobata'

In [23]:
df.iloc[[0, 1]]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [26]:
#Index(['RowNumber','CustomerId', 'Surname'], dtype='object')

NameError: name 'Index' is not defined

In [28]:
df.iloc[[0, 1], [1, 2]]

   CustomerId   Surname
0    15634602  Hargrave
1    15647311      Hill

In [29]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [39]:
df.loc[[1,2], ['Surname', 'CreditScore']]

  Surname  CreditScore
1    Hill          608
2    Onio          502

In [40]:
df.loc[[1,2], ['CreditScore', 'Surname']]

   CreditScore Surname
1          608    Hill
2          502    Onio

In [56]:
df.set_index('Surname', inplace=True)

In [60]:
df.sort_index(ascending=False)

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
Surname,,,,,,,,,,,,
Zuyeva,15689952,724,Spain,Male,41,5,0.00,1,0,1,115753.94,0
Zuyeva,15706810,606,Germany,Female,32,1,106301.85,2,0,1,59061.25,0
Zuyev,15722010,621,Spain,Male,53,9,170491.84,1,1,0,35588.07,1
Zuyev,15583394,659,Germany,Male,39,8,106259.63,2,1,1,198103.32,0
Zuev,15681174,730,France,Male,39,1,116537.60,1,0,0,145679.60,0
...,...,...,...,...,...,...,...,...,...,...,...,...
Abbott,15684801,689,France,Male,47,1,93871.95,3,1,0,156878.42,1
Abbott,15680804,850,France,Male,29,6,0.00,2,1,1,10672.54,0
Abbie,15737792,818,France,Female,31,1,186796.37,1,0,0,178252.63,0
Abazu,15576156,710,Spain,Female,28,6,0.00,1,1,0,48426.98,0
Abazu,15708791,584,Spain,Male,32,9,85534.83,1,0,0,169137.24,0

In [59]:
df

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
Surname,,,,,,,,,,,,
Hargrave,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
Hill,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
Onio,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
Boni,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
Mitchell,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
Obijiaku,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
Johnstone,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
Liu,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
Sabbatini,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
Walker,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [48]:
df.loc['Liu', 'Gender']

Surname
Liu      Male
Liu      Male
Liu      Male
Liu    Female
Liu      Male
Liu      Male
Liu      Male
Liu    Female
Liu      Male
Liu      Male
Liu    Female
Liu    Female
Name: Gender, dtype: object

In [50]:
df.iloc[0]

RowNumber                  1
CustomerId          15634602
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: Hargrave, dtype: object

In [54]:
df.reset_index(inplace=True)
df

,level_0,index,Surname,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,0,Hargrave,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,1,1,Hill,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2,2,Onio,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,3,3,Boni,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,4,4,Mitchell,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,9995,Obijiaku,9996,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9996,9996,Johnstone,9997,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9997,9997,Liu,9998,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9998,9998,Sabbatini,9999,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,9999,9999,Walker,10000,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0